# http://docs.travis-ci.com/user/build-configuration/

language: python

python:
    - "3.4"
    
services:
    - postgresql

sudo: false

notifications:
  slack: swedishchefs:nnxnMlhhs96km2J9KozWHPiB

install:
    - pip install --upgrade pip
    - pip --version
    - pip install coverage
    - pip install Flask
    - pip install sqlalchemy
    - pip install flask-restful
    - pip install psycopg2

before_script:
    - uname -a
    - printenv
    - pip list
    - psql -c 'create database travis_ci_test;' -U postgres

script:
    - date
    - ls -al
    - make models.html
    - ls -al
    - make IDB2.log
    - ls -al
    - make test
    - ls -al
    - make check
