# http://docs.travis-ci.com/user/build-configuration/

language: python

python:
    - "3.4"

sudo: false

notifications:
  slack: swedishchefs:nnxnMlhhs96km2J9KozWHPiB

install:
    - pip install --upgrade pip
    - pip --version
    - pip install coverage
    - pip install Flask
    - pip install sqlalchemy 

before_script:
    - uname -a
    - printenv
    - pip list

script:
    - date
    - ls -al
    - make model.html
    - ls -al
    - make IDB1.log
    - ls -al
    - make test
    - ls -al
    - make check
