FORMAT: 1A
HOST: http://api.swedishchef.me/

# RESTipe

RESTipe is a rich API allowing users to query recipes and ingredients, with lots of helpful information for both.

## Recipes Collection [/recipes]

### List All Recipe IDs [GET]

+ Response 200 (application/json)

        [
            8675309,
            88,
            373,
            ...
        ]

### List All Recipe IDs With Given Attributes [GET]

+ Response 200 (application/json)

        [
        
        ]

## Single Recipe [/recipes/{id}]