version: "2"

# A Docker Compose file for configuration of the production environment

services:
  lb:
    extends:
      file: docker-compose-common.yml
      service: lb
    image: cs373idb/cs373idb_lb
    environment:
      # Always deploy to n1 so the lb always has the same IP address. This is
      # just for convenience and isn't strictly necessary.
      - "constraint:node==*n1"

  app:
    extends:
      file: docker-compose-common.yml
      service: app
    image: cs373idb/cs373idb_app
    expose:
      # Expose port 5000 so it's only visibile on the container, not the host
      - "5000"
    env_file: cs373-postgres-prod.env
    command: gunicorn app:app --bind 0.0.0.0:5000
      # Run Gunicorn to serve app requests

  db:
    extends:
      file: docker-compose-common.yml
      service: db
    image: cs373idb/cs373idb_db
    expose:
      # Expose port 5432 so it's only visibile on the container, not the host
      - "5432"
    env_file:
      - cs373-postgres-prod.env

networks:
  backend: {}
